routes/web.php
<?php

use App\Models\Toko;
use Illuminate\Http\Request;
use App\Http\Livewire\LaporanToko;
use App\Http\Livewire\InputLaporan;
use App\Http\Livewire\UserManagement;
use Illuminate\Support\Facades\Route;
use Illuminate\Contracts\Database\Query\Builder;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('newWelcome');
});

Route::prefix('get-data')->as('get.')->group(function () {
    Route::get('toko', fn(Request $request) => Toko::when($request->search,fn(Builder $query) => $query->where('nama_toko','like', "%{$request->search}%"))->orderBy('nama_toko')->get())->name('toko');
}); 

Route::middleware(['auth:sanctum',config('jetstream.auth_session'),'verified'])->group(function () {
    Route::get('/dashboard', LaporanToko::class)->name('dashboard')->middleware('role:super_admin|admin_toko|developer');
    Route::get('/input-laporan', InputLaporan::class)->name('input-laporan')->middleware('role:inputer|developer');
    Route::get('/user-management',UserManagement::class)->name('user-management')->middleware('role:super_admin|developer');
});

app/Http/Livewire/Chart.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\LaporanToko;

class Chart extends Component
{
    public $label;
    public $total;

    public function mount()
    {
        $data = LaporanToko::with('toko')->get();
        $label = $data->pluck('toko.nama_toko')->unique();
        $total = $data->groupBy('toko_id')->map(fn($item) => $item->pluck('total')->sum());

        // dd($total);

        $this->label = json_encode($label);
        $this->total = json_encode($total);
    }

    public function render()
    {
        return view('livewire.chart');
    }
}

app/Http/Livewire/InputLaporan.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\LaporanToko;
use Livewire\WithFileUploads;
use WireUi\Traits\Actions;

class InputLaporan extends Component
{
    use WithFileUploads,Actions;
    
    public $toko_id,$date,$total;
    public $nota;

    public function updatedNota()
    {
        $this->validate([
            'nota' => 'mimes:pdf',
        ]);
    }

    public function resetFile()
    {
        $this->nota = null;
    }

    public function resetForm()
    {
        $this->toko_id = null;
        $this->date = null;
        $this->total = null;
        $this->nota = null;
    }

    public function save()
    {
        $this->validate([
            'toko_id' => 'required',
            'date' => 'required',
            'total' => 'required',
        ]);

        $filename = 'Laporan_Toko_'.$this->toko_id.$this->date.'.'.$this->nota->extension();
        $this->nota->storeAs('nota',$filename,'local');

        LaporanToko::create([
            'toko_id' => $this->toko_id,
            'date' => $this->date,
            'total' => $this->total,
            'nota_file' => $filename,
        ]);

        $this->resetForm();
        $this->notification()->success(
            $title = 'Store Report saved',
            $description = 'Your Resport was successfull saved'
        );
    }

    public function render()
    {
        return view('livewire.input-laporan');
    }
}

app/Http/Livewire/LaporanToko.php
<?php

namespace App\Http\Livewire;

use App\Models\Toko;
use Livewire\Component;
use Illuminate\Support\Carbon;
use App\Models\LaporanToko as Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;

class LaporanToko extends Component
{
    public $filter_date = 'Semua';
    public $filter_toko;

    public function download()
    {
        return response()->download(storage_path('exports/export.csv'));
    }

    public function render()
    {
        $data = Model::query()
        ->with('toko')
        ->when(!Auth::user()->hasRole(['super_admin','developer']),fn($query) => $query->whereHas('toko',fn(Builder $q) => $q->where('user_id',Auth::user()->id)))
        ->when($this->filter_date == 'Semua',fn($query) => $query)
        ->when($this->filter_date == 'Harian',fn($query) => $query->whereDay('date', '=',Carbon::now()))
        ->when($this->filter_date == 'Mingguan',fn($query) => $query->whereBetween('date',[Carbon::now()->startOfWeek(),Carbon::now()->endOfWeek()]))
        ->when($this->filter_date == 'Bulanan',fn($query) => $query->whereMonth('date','=',Carbon::now()->month))
        ->when($this->filter_toko, fn($query,$filter_toko) => $query->where('toko_id',$filter_toko))
        ->get();

        // dd($data);
        return view('livewire.laporan-toko',[
            'data' => $data,
            'stores' => Toko::all(),
        ]);
    }
}

app/Http/Livewire/UserManagement.php
<?php

namespace App\Http\Livewire;

use App\Models\Toko;
use App\Models\User;
use Livewire\Component;
use WireUi\Traits\Actions;
use Spatie\Permission\Models\Role;

class UserManagement extends Component
{
    use Actions;

    public $cardModal = false;
    public $name, $username, $email, $role;
    public $nama_toko, $owner;
    public $showFormToko = false;

    public function updatedRole()
    {
        // $this->showFormToko = true;
    }

    public function save()
    {
        $this->validate([
            'name' => 'required',
            'username' => 'required|unique:users,username',
            'email' => 'required|unique:users,email',
            'role' => 'required',
        ]);

        $newUser = User::factory()->create([
            'name' => $this->name,
            'username' => $this->username,
            'email' => $this->email,
        ]);
        $newUser->assignRole($this->role);

        if ($this->role == 2) {
            Toko::create([
                'nama_toko' => $this->nama_toko,
                'owner' => $this->owner,
                'user_id' => $newUser->id,
            ]);
        }

        $this->resetForm();
        $this->notification()->success(
            $title = 'New User Has benn saved',
            $description = 'User was successfull added'
        );
    }

    public function resetForm()
    {
        $this->name = null;
        $this->username = null;
        $this->email = null;
        $this->nama_toko = null;
        $this->owner = null;
        $this->cardModal = false;
    }

    public function render()
    {
        return view('livewire.user-management', [
            'users' => User::with('roles')->get(),
            'roles' => Role::all(),
        ]);
    }
}

resources/views/livewire/chart.blade.php
<div>
    <canvas id="myChart"></canvas>
    @push('js')
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
            var labelChart = JSON.parse(`<?php echo $label; ?>`);
            var totalChart = JSON.parse(`<?php echo $total; ?>`);
            console.log(Object.keys(labelChart).map(key => labelChart[key]));
            console.log(Object.keys(totalChart).map(key => totalChart[key]));
            const ctx = document.getElementById('myChart');

            new Chart(ctx, {
                type: 'polarArea',
                data: {
                    labels: Object.keys(labelChart).map(key => labelChart[key]),
                    datasets: [{
                        label: 'Total Penjualan',
                        data: Object.keys(totalChart).map(key => totalChart[key]),
                        backgroundColor: [
                            'rgb(255, 99, 132)',
                            'rgb(75, 192, 192)',
                            'rgb(255, 205, 86)',
                            'rgb(201, 203, 207)',
                            'rgb(54, 162, 235)'
                        ]
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    },
                    plugins: {
                        title: {
                            display: true,
                            text: 'Total Penjualan Toko'
                        }
                    }
                }
            });
        </script>
    @endpush
</div>

resources/views/livewire/input-laporan.blade.php
<div>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Input Laporan Toko') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-8">
                <div class="grid grid-cols-2 gap-4 ">
                    <div class="">
                        <x-select label="Select some Store" wire:model.defer="toko_id" placeholder="Search a Store"
                            :async-data="route('get.toko')" option-label="nama_toko" option-value="id" />
                    </div>
                    <div class="">
                        <x-datetime-picker label="Date" placeholder="Date" wire:model.defer="date" />
                    </div>
                    <div class="col-span-2">
                        <x-inputs.currency label="Total Penjualan" precision="0" icon="currency-dollar" thousands="."
                            decimal="," wire:model.defer="total" />
                    </div>
                    <div class="col-span-2">
                        <x-jet-label class="mb-1" for="nota" value="{{ __('Nota File') }}" />
                        @error('nota') <span class="text-red-500">{{ $message }}</span> @enderror
                        <div  x-data="{ files: null }"
                            class="grid grid-cols-2">
                            <label for="dropzone-file"
                                class="cursor-pointer flex w-full max-w-lg flex-col items-center rounded-xl border-2 border-dashed bg-white p-6 text-center {{$this->nota != null ? 'border-teal-400' : ''}} @error('nota') border-rose-400 @enderror ">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 text-blue-500" fill="none"
                                    viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round"
                                        d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                                </svg>

                                <h2 class="mt-4 text-xl font-medium text-gray-700 tracking-wide">Nota File</h2>

                                <p class="mt-2 text-gray-500 tracking-wide">Upload Nota File (.pdf)</p>

                                <input id="dropzone-file"
                                    type="file" x-on:change="files = Object.values($event.target.files)" wire:model='nota' class="hidden" />
                            </label>
                            <img wire:loading wire:target="nota" class="mx-auto my-auto" src="/Fidget-spinner.gif" alt="loading">
                            <div x-show='$wire.nota != null' class=" h-12 rounded-md bg-[#F5F7FB] py-3 px-4">
                                <div class="flex items-center justify-between">
                                    <span x-text="files?.map(file => file.name).join(', ')"
                                        class="truncate pr-3 text-base font-medium text-[#07074D]"></span>
                                    <button x-on:click="files = null" wire:click="resetFile" type="reset"
                                        class="text-[#07074D] hover:text-red-400">
                                        <svg width="10" height="10" viewBox="0 0 10 10" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd"
                                                d="M0.279337 0.279338C0.651787 -0.0931121 1.25565 -0.0931121 1.6281 0.279338L9.72066 8.3719C10.0931 8.74435 10.0931 9.34821 9.72066 9.72066C9.34821 10.0931 8.74435 10.0931 8.3719 9.72066L0.279337 1.6281C-0.0931125 1.25565 -0.0931125 0.651788 0.279337 0.279338Z"
                                                fill="currentColor" />
                                            <path fill-rule="evenodd" clip-rule="evenodd"
                                                d="M0.279337 9.72066C-0.0931125 9.34821 -0.0931125 8.74435 0.279337 8.3719L8.3719 0.279338C8.74435 -0.0931127 9.34821 -0.0931123 9.72066 0.279338C10.0931 0.651787 10.0931 1.25565 9.72066 1.6281L1.6281 9.72066C1.25565 10.0931 0.651787 10.0931 0.279337 9.72066Z"
                                                fill="currentColor" />
                                        </svg>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="flex items-center justify-end mt-4">
                    <x-button wire:click='save'  label="Save" positive right-icon="check-circle" />
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/laporan-toko.blade.php
<div>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @hasanyrole('super_admin|developer')
            <div class="bg-white overflow-hidden shadow-xl mb-5 sm:rounded-lg p-5 w-1/2 h-1/2">
                <livewire:chart/>
            </div>
            @endhasanyrole
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-5">
                <!-- component -->
                <div class="grid grid-cols-4 gap-3 px-5">
                    <x-select label="Filter Date" placeholder="Filter Data By Date" :options="['Semua','Harian', 'Mingguan', 'Bulanan']"
                    wire:model="filter_date" />
                    @hasanyrole('super_admin|developer')
                    <x-select label="Filter Toko" placeholder="Filter Data By Toko" :options="$stores"
                    wire:model="filter_toko" option-label="nama_toko" option-value="id" />
                    @endhasanyrole
                </div>
                <div class="overflow-x-auto">
                    <div class="flex items-center justify-centerfont-sans">
                        <div class="w-full p-5">
                            <div class="bg-white shadow-md rounded-lg">
                                <table class="min-w-max w-full table-auto">
                                    <thead>
                                        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                            <th class="py-3 px-6 text-left">Nama Toko</th>
                                            <th class="py-3 px-6 text-left">Date</th>
                                            <th class="py-3 px-6 text-center">Total Penjualan</th>
                                            <th class="py-3 px-6 text-center">Nota File</th>
                                            {{-- <th class="py-3 px-6 text-center">Actions</th> --}}
                                        </tr>
                                    </thead>
                                    <tbody class="text-gray-600 text-sm font-light">
                                        @forelse ($data as $item)
                                            <tr class="border-b border-gray-200 hover:bg-gray-100">
                                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                                    <div class="flex items-center">
                                                        <span class="font-medium">{{ $item->toko->nama_toko }}</span>
                                                    </div>
                                                </td>
                                                <td class="py-3 px-6 text-left">
                                                    <div class="flex items-center">
                                                        <span>{{ Carbon\Carbon::create($item->date)->format('D, d M Y') }}</span>
                                                    </div>
                                                </td>
                                                <td class="py-3 px-6 text-center">
                                                    <span> Rp. {{ number_format($item->total,0) }}</span>
                                                </td>
                                                <td class="py-3 px-6 text-center">
                                                    <button wire:click='download' class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs cursor-pointer">{{ $item->nota_file }}</button>
                                                </td>
                                                {{-- <td class="py-3 px-6 text-center">
                                                    <div class="flex item-center justify-center">
                                                        <div
                                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                viewBox="0 0 24 24" stroke="currentColor">
                                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                                    stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                                    stroke-width="2"
                                                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                                            </svg>
                                                        </div>
                                                        <div
                                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                viewBox="0 0 24 24" stroke="currentColor">
                                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                                    stroke-width="2"
                                                                    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                                            </svg>
                                                        </div>
                                                        <div
                                                            class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                viewBox="0 0 24 24" stroke="currentColor">
                                                                <path stroke-linecap="round" stroke-linejoin="round"
                                                                    stroke-width="2"
                                                                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                            </svg>
                                                        </div>
                                                    </div>
                                                </td> --}}
                                            </tr>
                                        @empty
                                            <span>Kosong</span>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/livewire/user-management.blade.php
<div>
    <x-modal.card title="Tambah User Baru" wire:model.defer="cardModal">
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <x-input wire:model='name' label="Name" placeholder="Your Fullname" />
            <x-input wire:model='username' label="Username" placeholder="Your Username" />

            <div class="col-span-1 sm:col-span-2">
                <x-input wire:model='email' label="Email" placeholder="example@mail.com" />
                <x-select label="Role" placeholder="Role User" :options="$roles" wire:model="role" option-label="name"
                    option-value="id" />
            </div>
            @if ($role == 2)
                <hr class="col-span-2">
                <x-input wire:model='nama_toko' label="Nama Toko" placeholder="Your Storename" />
                <x-input wire:model='owner' label="Owner" placeholder="Your Owner Name" />
            @endif
        </div>

        <x-slot name="footer">
            <div class="flex justify-between gap-x-4">
                <div class="flex">
                    <x-button flat label="Cancel" x-on:click="close" />
                    <x-button primary label="Save" wire:click="save()" />
                </div>
            </div>
        </x-slot>
    </x-modal.card>
    <div>
        <x-slot name="header">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('User Management') }}
            </h2>
        </x-slot>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg p-5">
                    <!-- component -->
                    <div class="px-5">
                        <x-button wire:click="$set('cardModal', true)" icon="pencil" primary label="User Baru" />
                    </div>
                    <div class="overflow-x-auto">
                        <div class="flex items-center justify-centerfont-sans">
                            <div class="w-full p-5">
                                <div class="bg-white shadow-md rounded-lg">
                                    <table class="min-w-max w-full table-auto">
                                        <thead>
                                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                                <th class="py-3 px-6 text-left">Nama User</th>
                                                <th class="py-3 px-6 text-left">Username</th>
                                                <th class="py-3 px-6 text-center">Email</th>
                                                <th class="py-3 px-6 text-center">Role</th>
                                                {{-- <th class="py-3 px-6 text-center">Actions</th> --}}
                                            </tr>
                                        </thead>
                                        <tbody class="text-gray-600 text-sm font-light">
                                            @forelse ($users as $user)
                                                <tr class="border-b border-gray-200 hover:bg-gray-100">
                                                    <td class="py-3 px-6 text-left whitespace-nowrap">
                                                        <div class="flex items-center">
                                                            <div class="mr-2">
                                                                <img class="h-8 w-8 rounded-full object-cover" src="{{ $user->profile_photo_url }}" alt="{{ $user->name }}" />
                                                            </div>
                                                            <span class="font-medium">{{ $user->name }}</span>
                                                        </div>
                                                    </td>
                                                    <td class="py-3 px-6 text-left">
                                                        <div class="flex items-center">
                                                            {{-- <div class="mr-2">
                                                                <img class="w-6 h-6 rounded-full"
                                                                    src="https://randomuser.me/api/portraits/men/1.jpg" />
                                                            </div> --}}
                                                            <span>{{ $user->username }}</span>
                                                        </div>
                                                    </td>
                                                    <td class="py-3 px-6 text-center">
                                                        <span>{{ $user->email }}</span>
                                                        {{-- <div class="flex items-center justify-center">
                                                            <img class="w-6 h-6 rounded-full border-gray-200 border transform hover:scale-125"
                                                                src="https://randomuser.me/api/portraits/men/1.jpg" />
                                                            <img class="w-6 h-6 rounded-full border-gray-200 border -m-1 transform hover:scale-125"
                                                                src="https://randomuser.me/api/portraits/women/2.jpg" />
                                                            <img class="w-6 h-6 rounded-full border-gray-200 border -m-1 transform hover:scale-125"
                                                                src="https://randomuser.me/api/portraits/men/3.jpg" />
                                                        </div> --}}
                                                    </td>
                                                    <td class="py-3 px-6 text-center">
                                                        <span
                                                            class="bg-purple-200 text-purple-600 py-1 px-3 rounded-full text-xs">
                                                            {{ $user->roles[0]->name }}
                                                        </span>
                                                    </td>
                                                    {{-- <td class="py-3 px-6 text-center">
                                                        <div class="flex item-center justify-center">
                                                            <div
                                                                class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                    viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                                        stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                                        stroke-width="2"
                                                                        d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                                                </svg>
                                                            </div>
                                                            <div
                                                                class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                    viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                                        stroke-width="2"
                                                                        d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                                                </svg>
                                                            </div>
                                                            <div
                                                                class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                                <svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                    viewBox="0 0 24 24" stroke="currentColor">
                                                                    <path stroke-linecap="round" stroke-linejoin="round"
                                                                        stroke-width="2"
                                                                        d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                                </svg>
                                                            </div>
                                                        </div>
                                                    </td> --}}
                                                </tr>
                                            @empty
                                                <span>Kosong</span>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>